name: AndroidBuild
on:
  pull_request:
    branches: [ master, main, uat ]
  push:
    branches: [ master, main, uat ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'adopt'


      - name: Get Gradle Version
        uses: KyoriPowered/get-gradle-versions@v2.0.0

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build

      - name: Set APK Name
        run: echo "APK_NAME=$(echo ${{ github.ref_name }}).apk" >> $GITHUB_ENV

      - name: Development APK
        if: github.ref == 'refs/heads/main'
        run: echo "Development APK build process"
        # Add your specific development build commands here, if any

      - name: Testing APK
        if: github.ref == 'refs/heads/uat'
        run: echo "Testing APK build process"
        # Add your specific testing build commands here, if any

      - name: Release APK
        if: github.ref == 'refs/heads/master'
        run: echo "Release APK build process"
        # Add your specific release build commands here, if any

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: ${{ env.APK_NAME }}
          path: app/build/outputs/apk/debug/app-debug.apk




